// Ontology Model Definition
export interface BaseWork {
  id: number;
  title: string;
  creatorIds: number[]; // References to Person IDs
  type: "Film" | "Book" | "Painting";
  genre: string;
  theme: string;
  period: string;
  relatedWorks: number[]; // References to related work IDs
}

// différents type d'oeuvre avec différentes propriétés
export interface Film extends BaseWork {
  type: "Film";
  duration: number;
  studio: string;
  actors: number[];
}

export interface Book extends BaseWork {
  type: "Book";
  narrativeType: string;
  pageCount: number;
}

export interface Painting extends BaseWork {
  type: "Painting";
  medium: string;
  dimensions: { width: number; height: number };
  location: string;
}

// Personne
export interface Person {
  id: number;
  name: string;
  birthYear?: number;
  deathYear?: number;
  roles: ("Author" | "Actor" | "Director" | "Painter")[];
  works: number[];
}

export type Work = Film | Book | Painting;

export const persons: Person[] = [
  {
    id: 1,
    name: "Vincent van Gogh",
    birthYear: 1853,
    deathYear: 1890,
    roles: ["Painter"],
    works: [1, 16, 18],
  },
  {
    id: 2,
    name: "Salvador Dalí",
    birthYear: 1904,
    deathYear: 1989,
    roles: ["Painter"],
    works: [2],
  },
  {
    id: 3,
    name: "Victor Hugo",
    birthYear: 1802,
    deathYear: 1885,
    roles: ["Author"],
    works: [3],
  },
  {
    id: 4,
    name: "Francis Ford Coppola",
    birthYear: 1939,
    roles: ["Director"],
    works: [4],
  },
  {
    id: 5,
    name: "Marlon Brando",
    birthYear: 1924,
    deathYear: 2004,
    roles: ["Actor"],
    works: [4],
  },
  {
    id: 6,
    name: "Leonardo da Vinci",
    birthYear: 1452,
    deathYear: 1519,
    roles: ["Painter"],
    works: [5],
  },
  {
    id: 7,
    name: "Olivier Nakache",
    birthYear: 1973,
    roles: ["Director"],
    works: [6],
  },
  { id: 8, name: "Omar Sy", birthYear: 1978, roles: ["Actor"], works: [6] },
  {
    id: 9,
    name: "Jean Cocteau",
    birthYear: 1889,
    deathYear: 1963,
    roles: ["Director"],
    works: [7],
  },
  {
    id: 10,
    name: "Josette Day",
    birthYear: 1914,
    deathYear: 1978,
    roles: ["Actor"],
    works: [7],
  },
  {
    id: 11,
    name: "Gustave Flaubert",
    birthYear: 1821,
    deathYear: 1880,
    roles: ["Author"],
    works: [8],
  },
  {
    id: 12,
    name: "Pablo Picasso",
    birthYear: 1881,
    deathYear: 1973,
    roles: ["Painter"],
    works: [9, 21],
  },
  {
    id: 13,
    name: "Antoine de Saint-Exupéry",
    birthYear: 1900,
    deathYear: 1944,
    roles: ["Author"],
    works: [10],
  },
  {
    id: 14,
    name: "Charles Baudelaire",
    birthYear: 1821,
    deathYear: 1867,
    roles: ["Author"],
    works: [11],
  },
  {
    id: 15,
    name: "Jean-Pierre Jeunet",
    birthYear: 1953,
    roles: ["Director"],
    works: [12],
  },
  {
    id: 16,
    name: "Audrey Tautou",
    birthYear: 1976,
    roles: ["Actor"],
    works: [12],
  },
  {
    id: 17,
    name: "George A. Romero",
    birthYear: 1940,
    deathYear: 2017,
    roles: ["Director"],
    works: [13],
  },
  {
    id: 18,
    name: "Claude Monet",
    birthYear: 1840,
    deathYear: 1926,
    roles: ["Painter"],
    works: [14],
  },
  {
    id: 19,
    name: "François Truffaut",
    birthYear: 1932,
    deathYear: 1984,
    roles: ["Director"],
    works: [15],
  },
  {
    id: 20,
    name: "Marcel Proust",
    birthYear: 1871,
    deathYear: 1922,
    roles: ["Author"],
    works: [17],
  },
  {
    id: 21,
    name: "Jonathan Demme",
    birthYear: 1944,
    deathYear: 2017,
    roles: ["Director"],
    works: [19],
  },
  {
    id: 22,
    name: "Howard Phillips Lovecraft",
    birthYear: 1890,
    deathYear: 1937,
    roles: ["Author"],
    works: [20],
  },
  {
    id: 23,
    name: "Vin Diesel",
    birthYear: 1967,
    roles: ["Actor"],
    works: [22, 23, 24, 25, 26, 27, 28, 29, 30],
  },
  {
    id: 24,
    name: "Paul Walker",
    birthYear: 1973,
    deathYear: 2013,
    roles: ["Actor"],
    works: [22, 23, 24, 25, 26],
  },
  {
    id: 25,
    name: "Justin Lin",
    birthYear: 1971,
    roles: ["Director"],
    works: [22, 23, 25, 26, 27, 28, 29],
  },
  {
    id: 26,
    name: "Jules Verne",
    birthYear: 1828,
    deathYear: 1905,
    roles: ["Author"],
    works: [31, 32, 33, 34, 35, 36, 50, 51, 52],
  },
  {
    id: 27,
    name: "Victor Hugo",
    birthYear: 1802,
    deathYear: 1885,
    roles: ["Author"],
    works: [37, 38, 39, 40, 3, 53, 54, 55],
  },
  {
    id: 28,
    name: "Daniel Radcliffe",
    birthYear: 1989,
    roles: ["Actor"],
    works: [41, 42, 43, 44, 45, 46, 47, 48],
  },
  {
    id: 29,
    name: "Emma Watson",
    birthYear: 1990,
    roles: ["Actor"],
    works: [41, 42, 43, 44, 45, 46, 47, 48],
  },
  {
    id: 30,
    name: "Rupert Grint",
    birthYear: 1988,
    roles: ["Actor"],
    works: [41, 42, 43, 44, 45, 46, 47, 48],
  },
  {
    id: 31,
    name: "Agatha Christie",
    birthYear: 1890,
    deathYear: 1976,
    roles: ["Author"],
    works: [56, 57, 58, 59, 60],
  },
  {
    id: 32,
    name: "Stephen King",
    birthYear: 1947,
    roles: ["Author"],
    works: [61, 62, 63, 64, 65],
  },

  {
    id: 33,
    name: "Claude Monet",
    birthYear: 1840,
    deathYear: 1926,
    roles: ["Painter"],
    works: [66, 67, 68, 69, 70],
  },
  {
    id: 34,
    name: "Paul Cézanne",
    birthYear: 1839,
    deathYear: 1906,
    roles: ["Painter"],
    works: [71, 72, 73, 74, 75],
  },

  {
    id: 35,
    name: "Christopher Nolan",
    birthYear: 1970,
    roles: ["Director"],
    works: [76, 77, 78, 79, 80],
  },
  {
    id: 36,
    name: "Steven Spielberg",
    birthYear: 1946,
    roles: ["Director"],
    works: [81, 82, 83, 84, 85],
  },

  {
    id: 37,
    name: "Meryl Streep",
    birthYear: 1949,
    roles: ["Actor"],
    works: [86, 87, 88, 89, 90],
  },
  {
    id: 38,
    name: "Tom Hanks",
    birthYear: 1956,
    roles: ["Actor"],
    works: [91, 92, 93, 94, 95],
  },
  {
    id: 39,
    name: "Maurice Pialat",
    birthYear: 1925,
    deathYear: 2003,
    roles: ["Director"],
    works: [78],
  },
  {
    id: 40,
    name: "Jacques Dutronc",
    birthYear: 1943,
    roles: ["Actor"],
    works: [78],
  },
];

export const works: Work[] = [
  {
    id: 1,
    title: "La Nuit étoilée",
    creatorIds: [1],
    type: "Painting",
    genre: "Post-Impressionnisme",
    theme: "Nature",
    period: "1889",
    relatedWorks: [],
    medium: "Huile",
    dimensions: { width: 73, height: 92 },
    location: "Musée d'Art Moderne, New York",
  },
  {
    id: 2,
    title: "La Persistance de la mémoire",
    creatorIds: [2],
    type: "Painting",
    genre: "Surréalisme",
    theme: "Temps",
    period: "1931",
    relatedWorks: [],
    medium: "Huile",
    dimensions: { width: 24, height: 33 },
    location: "Musée d'Art Moderne, New York",
  },
  {
    id: 3,
    title: "Les Misérables",
    creatorIds: [3],
    type: "Book",
    genre: "Historique",
    theme: "Révolution, Rédemption",
    period: "1862",
    relatedWorks: [],
    narrativeType: "Omniscient",
    pageCount: 1500,
  },
  {
    id: 4,
    title: "Le Parrain",
    creatorIds: [4],
    type: "Film",
    genre: "Drame",
    theme: "Famille",
    period: "1972",
    relatedWorks: [],
    duration: 175,
    studio: "Paramount Pictures",
    actors: [5],
  },
  {
    id: 5,
    title: "La Joconde",
    creatorIds: [6],
    type: "Painting",
    genre: "Renaissance",
    theme: "Beauté",
    period: "1503-1519",
    relatedWorks: [],
    medium: "Huile",
    dimensions: { width: 77, height: 53 },
    location: "Musée du Louvre, Paris",
  },
  {
    id: 6,
    title: "Intouchables",
    creatorIds: [7, 8],
    type: "Film",
    genre: "Comédie, Drame",
    theme: "Amitié, Résilience",
    period: "2011",
    relatedWorks: [],
    duration: 112,
    studio: "Gaumont",
    actors: [8],
  },
  {
    id: 7,
    title: "La Belle et la Bête",
    creatorIds: [9],
    type: "Film",
    genre: "Fantastique, Romance",
    theme: "Transformation, Amour",
    period: "2014",
    relatedWorks: [],
    duration: 112,
    studio: "Pathé",
    actors: [10],
  },
  {
    id: 8,
    title: "Madame Bovary",
    creatorIds: [11],
    type: "Book",
    genre: "Drame",
    theme: "Mariage, Société",
    period: "1857",
    relatedWorks: [],
    narrativeType: "Omniscient",
    pageCount: 380,
  },
  {
    id: 9,
    title: "Guernica",
    creatorIds: [12],
    type: "Painting",
    genre: "Cubisme",
    theme: "Guerre, Souffrance",
    period: "1937",
    relatedWorks: [],
    medium: "Huile",
    dimensions: { width: 349, height: 776 },
    location: "Museo Reina Sofía, Madrid",
  },
  {
    id: 10,
    title: "Le Petit Prince",
    creatorIds: [13],
    type: "Book",
    genre: "Philosophie, Fiction",
    theme: "Amitié, Imagination",
    period: "1943",
    relatedWorks: [],
    narrativeType: "Première Personne",
    pageCount: 96,
  },
  {
    id: 11,
    title: "Les Fleurs du mal",
    creatorIds: [14],
    type: "Book",
    genre: "Poésie",
    theme: "Beauté, Mélancolie",
    period: "1857",
    relatedWorks: [],
    narrativeType: "Omniscient",
    pageCount: 248,
  },
  {
    id: 12,
    title: "Le Fabuleux Destin d'Amélie Poulain",
    creatorIds: [15],
    type: "Film",
    genre: "Comédie Romantique",
    theme: "Espoir, Solitude",
    period: "2001",
    relatedWorks: [],
    duration: 122,
    studio: "Claudie Ossard Productions",
    actors: [16],
  },
  {
    id: 13,
    title: "La Nuit des morts-vivants",
    creatorIds: [17],
    type: "Film",
    genre: "Horreur",
    theme: "Survie, Terreur",
    period: "1968",
    relatedWorks: [],
    duration: 96,
    studio: "Image Ten",
    actors: [],
  },
  {
    id: 14,
    title: "Impression, soleil levant",
    creatorIds: [18],
    type: "Painting",
    genre: "Impressionnisme",
    theme: "Paysage, Lumière",
    period: "1872",
    relatedWorks: [],
    medium: "Huile",
    dimensions: { width: 48, height: 63 },
    location: "Musée Marmottan Monet, Paris",
  },
  {
    id: 15,
    title: "Le Dernier Métro",
    creatorIds: [19],
    type: "Film",
    genre: "Drame, Romance",
    theme: "Résistance, Amour",
    period: "1980",
    relatedWorks: [],
    duration: 131,
    studio: "Les Films du Carrosse",
    actors: [],
  },
  {
    id: 16,
    title: "Sunflowers",
    creatorIds: [1],
    type: "Painting",
    genre: "Post-Impressionnisme",
    theme: "Nature, Beauté",
    period: "1888",
    relatedWorks: [],
    medium: "Huile",
    dimensions: { width: 92, height: 73 },
    location: "Van Gogh Museum, Amsterdam",
  },
  {
    id: 17,
    title: "La Recherche du temps perdu",
    creatorIds: [20],
    type: "Book",
    genre: "Roman",
    theme: "Mémoire, Nostalgie",
    period: "1913",
    relatedWorks: [],
    narrativeType: "Première Personne",
    pageCount: 4215,
  },
  {
    id: 18,
    title: "La Chambre rouge",
    creatorIds: [1],
    type: "Painting",
    genre: "Expressionnisme",
    theme: "Introspection, Mystère",
    period: "1908",
    relatedWorks: [],
    medium: "Huile",
    dimensions: { width: 81, height: 100 },
    location: "Centre Pompidou, Paris",
  },
  {
    id: 19,
    title: "Le Silence des agneaux",
    creatorIds: [21],
    type: "Film",
    genre: "Thriller, Horreur",
    theme: "Traque, Psychologie",
    period: "1991",
    relatedWorks: [],
    duration: 118,
    studio: "Orion Pictures",
    actors: [],
  },
  {
    id: 20,
    title: "À la recherche de l'inconnu",
    creatorIds: [22],
    type: "Book",
    genre: "Mystère",
    theme: "Aventure, Découverte",
    period: "1920",
    relatedWorks: [],
    narrativeType: "Omniscient",
    pageCount: 400,
  },
  {
    id: 21,
    title: "Les Demoiselles d'Avignon",
    creatorIds: [12],
    type: "Painting",
    genre: "Cubisme",
    theme: "Modernité, Rébellion",
    period: "1907",
    relatedWorks: [],
    medium: "Huile",
    dimensions: { width: 243.9, height: 233.7 },
    location: "Musée d'Art Moderne, New York",
  },
  {
    id: 22,
    title: "The Fast and the Furious",
    creatorIds: [25],
    type: "Film",
    genre: "Action",
    theme: "Street Racing",
    period: "2001",
    relatedWorks: [],
    duration: 106,
    studio: "Universal Pictures",
    actors: [23, 24],
  },
  {
    id: 23,
    title: "2 Fast 2 Furious",
    creatorIds: [25],
    type: "Film",
    genre: "Action",
    theme: "Street Racing",
    period: "2003",
    relatedWorks: [],
    duration: 107,
    studio: "Universal Pictures",
    actors: [24],
  },
  {
    id: 24,
    title: "The Fast and the Furious: Tokyo Drift",
    creatorIds: [25],
    type: "Film",
    genre: "Action",
    theme: "Street Racing",
    period: "2006",
    relatedWorks: [],
    duration: 104,
    studio: "Universal Pictures",
    actors: [23, 24],
  },
  {
    id: 25,
    title: "Fast & Furious",
    creatorIds: [25],
    type: "Film",
    genre: "Action",
    theme: "Street Racing",
    period: "2009",
    relatedWorks: [],
    duration: 107,
    studio: "Universal Pictures",
    actors: [23, 24],
  },
  {
    id: 26,
    title: "Fast Five",
    creatorIds: [25],
    type: "Film",
    genre: "Action",
    theme: "Heist",
    period: "2011",
    relatedWorks: [],
    duration: 130,
    studio: "Universal Pictures",
    actors: [23, 24],
  },
  {
    id: 27,
    title: "Fast & Furious 6",
    creatorIds: [25],
    type: "Film",
    genre: "Action",
    theme: "Heist",
    period: "2013",
    relatedWorks: [],
    duration: 130,
    studio: "Universal Pictures",
    actors: [23],
  },
  {
    id: 28,
    title: "Furious 7",
    creatorIds: [25],
    type: "Film",
    genre: "Action",
    theme: "Revenge",
    period: "2015",
    relatedWorks: [],
    duration: 137,
    studio: "Universal Pictures",
    actors: [23, 24],
  },
  {
    id: 29,
    title: "The Fate of the Furious",
    creatorIds: [25],
    type: "Film",
    genre: "Action",
    theme: "Betrayal",
    period: "2017",
    relatedWorks: [],
    duration: 136,
    studio: "Universal Pictures",
    actors: [23],
  },
  {
    id: 30,
    title: "F9",
    creatorIds: [25],
    type: "Film",
    genre: "Action",
    theme: "Family",
    period: "2021",
    relatedWorks: [],
    duration: 143,
    studio: "Universal Pictures",
    actors: [23],
  },
  {
    id: 41,
    title: "Harry Potter à l'école des sorciers",
    creatorIds: [],
    type: "Film",
    genre: "Fantasy",
    theme: "Amitié, Magie",
    period: "2001",
    relatedWorks: [],
    duration: 152,
    studio: "Warner Bros.",
    actors: [28, 29, 30],
  },
  {
    id: 42,
    title: "Harry Potter et la Chambre des secrets",
    creatorIds: [],
    type: "Film",
    genre: "Fantasy",
    theme: "Mystère, Magie",
    period: "2002",
    relatedWorks: [],
    duration: 161,
    studio: "Warner Bros.",
    actors: [28, 29, 30],
  },
  {
    id: 43,
    title: "Harry Potter et le Prisonnier d'Azkaban",
    creatorIds: [],
    type: "Film",
    genre: "Fantasy",
    theme: "Secrets, Famille",
    period: "2004",
    relatedWorks: [],
    duration: 142,
    studio: "Warner Bros.",
    actors: [28, 29, 30],
  },
  {
    id: 44,
    title: "Harry Potter et la Coupe de feu",
    creatorIds: [],
    type: "Film",
    genre: "Fantasy",
    theme: "Compétition, Danger",
    period: "2005",
    relatedWorks: [],
    duration: 157,
    studio: "Warner Bros.",
    actors: [28, 29, 30],
  },
  {
    id: 45,
    title: "Harry Potter et l'Ordre du Phénix",
    creatorIds: [],
    type: "Film",
    genre: "Fantasy",
    theme: "Rébellion, Résistance",
    period: "2007",
    relatedWorks: [],
    duration: 138,
    studio: "Warner Bros.",
    actors: [28, 29, 30],
  },
  {
    id: 46,
    title: "Harry Potter et le Prince de Sang-Mêlé",
    creatorIds: [],
    type: "Film",
    genre: "Fantasy",
    theme: "Amour, Tragédie",
    period: "2009",
    relatedWorks: [],
    duration: 153,
    studio: "Warner Bros.",
    actors: [28, 29, 30],
  },
  {
    id: 47,
    title: "Harry Potter et les Reliques de la Mort: Partie 1",
    creatorIds: [],
    type: "Film",
    genre: "Fantasy",
    theme: "Fuite, Danger",
    period: "2010",
    relatedWorks: [],
    duration: 146,
    studio: "Warner Bros.",
    actors: [28, 29, 30],
  },
  {
    id: 48,
    title: "Harry Potter et les Reliques de la Mort: Partie 2",
    creatorIds: [],
    type: "Film",
    genre: "Fantasy",
    theme: "Bataille, Courage",
    period: "2011",
    relatedWorks: [],
    duration: 130,
    studio: "Warner Bros.",
    actors: [28, 29, 30],
  },
  {
    id: 31,
    title: "Vingt mille lieues sous les mers",
    creatorIds: [26],
    type: "Book",
    genre: "Science-Fiction",
    theme: "Exploration",
    period: "1870",
    relatedWorks: [],
    narrativeType: "Omniscient",
    pageCount: 450,
  },
  {
    id: 32,
    title: "Le Tour du monde en 80 jours",
    creatorIds: [26],
    type: "Book",
    genre: "Aventure",
    theme: "Voyage",
    period: "1873",
    relatedWorks: [],
    narrativeType: "Omniscient",
    pageCount: 300,
  },
  {
    id: 33,
    title: "De la Terre à la Lune",
    creatorIds: [26],
    type: "Book",
    genre: "Science-Fiction",
    theme: "Exploration Spatiale",
    period: "1865",
    relatedWorks: [],
    narrativeType: "Omniscient",
    pageCount: 270,
  },
  {
    id: 34,
    title: "L'Île mystérieuse",
    creatorIds: [26],
    type: "Book",
    genre: "Aventure",
    theme: "Survie",
    period: "1874",
    relatedWorks: [],
    narrativeType: "Omniscient",
    pageCount: 620,
  },
  {
    id: 35,
    title: "Les Enfants du capitaine Grant",
    creatorIds: [26],
    type: "Book",
    genre: "Aventure",
    theme: "Exploration",
    period: "1867",
    relatedWorks: [],
    narrativeType: "Omniscient",
    pageCount: 350,
  },
  {
    id: 36,
    title: "Voyage au centre de la Terre",
    creatorIds: [26],
    type: "Book",
    genre: "Science-Fiction",
    theme: "Exploration",
    period: "1864",
    relatedWorks: [],
    narrativeType: "Omniscient",
    pageCount: 300,
  },
  {
    id: 37,
    title: "Notre-Dame de Paris",
    creatorIds: [27],
    type: "Book",
    genre: "Historique",
    theme: "Amour, Rébellion",
    period: "1831",
    relatedWorks: [],
    narrativeType: "Omniscient",
    pageCount: 940,
  },
  {
    id: 38,
    title: "Les Travailleurs de la mer",
    creatorIds: [27],
    type: "Book",
    genre: "Aventure",
    theme: "Survie",
    period: "1866",
    relatedWorks: [],
    narrativeType: "Omniscient",
    pageCount: 600,
  },
  {
    id: 39,
    title: "L'Homme qui rit",
    creatorIds: [27],
    type: "Book",
    genre: "Roman",
    theme: "Destin, Révolte",
    period: "1869",
    relatedWorks: [],
    narrativeType: "Omniscient",
    pageCount: 850,
  },
  {
    id: 40,
    title: "Quatrevingt-treize",
    creatorIds: [27],
    type: "Book",
    genre: "Historique",
    theme: "Révolution, Justice",
    period: "1874",
    relatedWorks: [],
    narrativeType: "Omniscient",
    pageCount: 900,
  },
  {
    id: 53,
    title: "Les Orientales",
    creatorIds: [27],
    type: "Book",
    genre: "Poésie",
    theme: "Exotisme, Réflexion",
    period: "1829",
    relatedWorks: [],
    narrativeType: "N/A",
    pageCount: 200,
  },
  {
    id: 54,
    title: "Les Contemplations",
    creatorIds: [27],
    type: "Book",
    genre: "Poésie",
    theme: "Mémoire, Nostalgie",
    period: "1856",
    relatedWorks: [],
    narrativeType: "N/A",
    pageCount: 500,
  },
  {
    id: 55,
    title: "La Légende des siècles",
    creatorIds: [27],
    type: "Book",
    genre: "Poésie",
    theme: "Histoire, Humanité",
    period: "1859",
    relatedWorks: [],
    narrativeType: "N/A",
    pageCount: 800,
  },
  {
    id: 56,
    title: "Le Meurtre de Roger Ackroyd",
    creatorIds: [31],
    type: "Book",
    genre: "Mystère",
    theme: "Crime",
    period: "1926",
    relatedWorks: [],
    narrativeType: "Omniscient",
    pageCount: 300,
  },
  {
    id: 57,
    title: "Mort sur le Nil",
    creatorIds: [31],
    type: "Book",
    genre: "Mystère",
    theme: "Enquête",
    period: "1937",
    relatedWorks: [],
    narrativeType: "Omniscient",
    pageCount: 288,
  },
  {
    id: 58,
    title: "Dix petits nègres",
    creatorIds: [31],
    type: "Book",
    genre: "Suspense",
    theme: "Crime",
    period: "1939",
    relatedWorks: [],
    narrativeType: "Omniscient",
    pageCount: 272,
  },
  {
    id: 59,
    title: "ABC contre Poirot",
    creatorIds: [31],
    type: "Book",
    genre: "Enquête",
    theme: "Crime",
    period: "1936",
    relatedWorks: [],
    narrativeType: "Omniscient",
    pageCount: 256,
  },
  {
    id: 60,
    title: "L'Orient-Express",
    creatorIds: [31],
    type: "Book",
    genre: "Mystère",
    theme: "Enquête",
    period: "1934",
    relatedWorks: [],
    narrativeType: "Omniscient",
    pageCount: 300,
  },

  {
    id: 61,
    title: "Carrie",
    creatorIds: [32],
    type: "Book",
    genre: "Horreur",
    theme: "Pouvoir, Revanche",
    period: "1974",
    relatedWorks: [],
    narrativeType: "Omniscient",
    pageCount: 199,
  },
  {
    id: 62,
    title: "Shining",
    creatorIds: [32],
    type: "Book",
    genre: "Horreur",
    theme: "Isolement",
    period: "1977",
    relatedWorks: [],
    narrativeType: "Omniscient",
    pageCount: 447,
  },
  {
    id: 63,
    title: "Ça",
    creatorIds: [32],
    type: "Book",
    genre: "Horreur",
    theme: "Peurs Enfantines",
    period: "1986",
    relatedWorks: [],
    narrativeType: "Omniscient",
    pageCount: 1138,
  },
  {
    id: 64,
    title: "Misery",
    creatorIds: [32],
    type: "Book",
    genre: "Suspense",
    theme: "Isolement, Obsession",
    period: "1987",
    relatedWorks: [],
    narrativeType: "Omniscient",
    pageCount: 310,
  },
  {
    id: 65,
    title: "La Ligne Verte",
    creatorIds: [32],
    type: "Book",
    genre: "Drame",
    theme: "Justice, Miracle",
    period: "1996",
    relatedWorks: [],
    narrativeType: "Omniscient",
    pageCount: 400,
  },

  {
    id: 66,
    title: "Les Coquelicots",
    creatorIds: [33],
    type: "Painting",
    genre: "Impressionnisme",
    theme: "Nature",
    period: "1873",
    relatedWorks: [],
    medium: "Huile",
    dimensions: { width: 50, height: 65 },
    location: "Musée d'Orsay, Paris",
  },
  {
    id: 67,
    title: "Impression, soleil levant",
    creatorIds: [33],
    type: "Painting",
    genre: "Impressionnisme",
    theme: "Lumière, Mer",
    period: "1872",
    relatedWorks: [],
    medium: "Huile",
    dimensions: { width: 48, height: 63 },
    location: "Musée Marmottan Monet, Paris",
  },
  {
    id: 68,
    title: "Nymphéas",
    creatorIds: [33],
    type: "Painting",
    genre: "Impressionnisme",
    theme: "Nature, Reflet",
    period: "1916",
    relatedWorks: [],
    medium: "Huile",
    dimensions: { width: 100, height: 200 },
    location: "Musée de l'Orangerie, Paris",
  },

  {
    id: 76,
    title: "Inception",
    creatorIds: [35],
    type: "Film",
    genre: "Science-Fiction",
    theme: "Rêves, Réalité",
    period: "2010",
    relatedWorks: [],
    duration: 148,
    studio: "Warner Bros.",
    actors: [],
  },
  {
    id: 77,
    title: "Interstellar",
    creatorIds: [35],
    type: "Film",
    genre: "Science-Fiction",
    theme: "Exploration Spatiale",
    period: "2014",
    relatedWorks: [],
    duration: 169,
    studio: "Paramount Pictures",
    actors: [],
  },
  {
    id: 78,
    title: "Van Gogh",
    creatorIds: [39],
    type: "Film",
    genre: "Biographie",
    theme: "Art, Vie",
    period: "1991",
    relatedWorks: [1],
    duration: 138,
    studio: "Paramount Pictures",
    actors: [40],
  },
];
