// Ontology Model Definition
export interface BaseWork {
  id: number;
  title: string;
  creatorIds: number[]; // References to Person IDs
  type: "Film" | "Book" | "Painting";
  genre: string;
  theme: string;
  period: string;
  relatedWorks: number[]; // References to related work IDs
}

// différents type d'oeuvre avec différentes propriétés
export interface Film extends BaseWork {
  type: "Film";
  duration: number;
  studio: string;
  actors: number[];
}

export interface Book extends BaseWork {
  type: "Book";
  narrativeType: string;
  pageCount: number;
}

export interface Painting extends BaseWork {
  type: "Painting";
  medium: string;
  dimensions: { width: number; height: number };
  location: string;
}

// Personne
export interface Person {
  id: number;
  name: string;
  birthYear?: number;
  deathYear?: number;
  roles: ("Author" | "Actor" | "Director" | "Painter")[];
  works: number[];
}

export type Work = Film | Book | Painting;

export const persons: Person[] = [
  {
    id: 1,
    name: "Vincent van Gogh",
    birthYear: 1853,
    deathYear: 1890,
    roles: ["Painter"],
    works: [1, 16, 18],
  },
  {
    id: 2,
    name: "Salvador Dalí",
    birthYear: 1904,
    deathYear: 1989,
    roles: ["Painter"],
    works: [2],
  },
  {
    id: 3,
    name: "Victor Hugo",
    birthYear: 1802,
    deathYear: 1885,
    roles: ["Author"],
    works: [3],
  },
  {
    id: 4,
    name: "Francis Ford Coppola",
    birthYear: 1939,
    roles: ["Director"],
    works: [4],
  },
  {
    id: 5,
    name: "Marlon Brando",
    birthYear: 1924,
    deathYear: 2004,
    roles: ["Actor"],
    works: [4],
  },
  {
    id: 6,
    name: "Leonardo da Vinci",
    birthYear: 1452,
    deathYear: 1519,
    roles: ["Painter"],
    works: [5],
  },
  {
    id: 7,
    name: "Olivier Nakache",
    birthYear: 1973,
    roles: ["Director"],
    works: [6],
  },
  { id: 8, name: "Omar Sy", birthYear: 1978, roles: ["Actor"], works: [6] },
  {
    id: 9,
    name: "Jean Cocteau",
    birthYear: 1889,
    deathYear: 1963,
    roles: ["Director"],
    works: [7],
  },
  {
    id: 10,
    name: "Josette Day",
    birthYear: 1914,
    deathYear: 1978,
    roles: ["Actor"],
    works: [7],
  },
  {
    id: 11,
    name: "Gustave Flaubert",
    birthYear: 1821,
    deathYear: 1880,
    roles: ["Author"],
    works: [8],
  },
  {
    id: 12,
    name: "Pablo Picasso",
    birthYear: 1881,
    deathYear: 1973,
    roles: ["Painter"],
    works: [9, 21],
  },
  {
    id: 13,
    name: "Antoine de Saint-Exupéry",
    birthYear: 1900,
    deathYear: 1944,
    roles: ["Author"],
    works: [10],
  },
  {
    id: 14,
    name: "Charles Baudelaire",
    birthYear: 1821,
    deathYear: 1867,
    roles: ["Author"],
    works: [11],
  },
  {
    id: 15,
    name: "Jean-Pierre Jeunet",
    birthYear: 1953,
    roles: ["Director"],
    works: [12],
  },
  {
    id: 16,
    name: "Audrey Tautou",
    birthYear: 1976,
    roles: ["Actor"],
    works: [12],
  },
  {
    id: 17,
    name: "George A. Romero",
    birthYear: 1940,
    deathYear: 2017,
    roles: ["Director"],
    works: [13],
  },
  {
    id: 18,
    name: "Claude Monet",
    birthYear: 1840,
    deathYear: 1926,
    roles: ["Painter"],
    works: [14],
  },
  {
    id: 19,
    name: "François Truffaut",
    birthYear: 1932,
    deathYear: 1984,
    roles: ["Director"],
    works: [15],
  },
  {
    id: 20,
    name: "Marcel Proust",
    birthYear: 1871,
    deathYear: 1922,
    roles: ["Author"],
    works: [17],
  },
  {
    id: 21,
    name: "Jonathan Demme",
    birthYear: 1944,
    deathYear: 2017,
    roles: ["Director"],
    works: [19],
  },
  {
    id: 22,
    name: "Howard Phillips Lovecraft",
    birthYear: 1890,
    deathYear: 1937,
    roles: ["Author"],
    works: [20],
  },
];

export const works: Work[] = [
  {
    id: 1,
    title: "La Nuit étoilée",
    creatorIds: [1],
    type: "Painting",
    genre: "Post-Impressionnisme",
    theme: "Nature",
    period: "1889",
    relatedWorks: [2],
    medium: "Huile",
    dimensions: { width: 73, height: 92 },
    location: "Musée d'Art Moderne, New York",
  },
  {
    id: 2,
    title: "La Persistance de la mémoire",
    creatorIds: [2],
    type: "Painting",
    genre: "Surréalisme",
    theme: "Temps",
    period: "1931",
    relatedWorks: [1],
    medium: "Huile",
    dimensions: { width: 24, height: 33 },
    location: "Musée d'Art Moderne, New York",
  },
  {
    id: 3,
    title: "Les Misérables",
    creatorIds: [3],
    type: "Book",
    genre: "Historique",
    theme: "Révolution, Rédemption",
    period: "1862",
    relatedWorks: [],
    narrativeType: "Omniscient",
    pageCount: 1500,
  },
  {
    id: 4,
    title: "Le Parrain",
    creatorIds: [4],
    type: "Film",
    genre: "Drame",
    theme: "Famille",
    period: "1972",
    relatedWorks: [],
    duration: 175,
    studio: "Paramount Pictures",
    actors: [5],
  },
  {
    id: 5,
    title: "La Joconde",
    creatorIds: [6],
    type: "Painting",
    genre: "Renaissance",
    theme: "Beauté",
    period: "1503-1519",
    relatedWorks: [],
    medium: "Huile",
    dimensions: { width: 77, height: 53 },
    location: "Musée du Louvre, Paris",
  },
  {
    id: 6,
    title: "Intouchables",
    creatorIds: [7, 8],
    type: "Film",
    genre: "Comédie, Drame",
    theme: "Amitié, Résilience",
    period: "2011",
    relatedWorks: [],
    duration: 112,
    studio: "Gaumont",
    actors: [8],
  },
  {
    id: 7,
    title: "La Belle et la Bête",
    creatorIds: [9],
    type: "Film",
    genre: "Fantastique, Romance",
    theme: "Transformation, Amour",
    period: "2014",
    relatedWorks: [],
    duration: 112,
    studio: "Pathé",
    actors: [10],
  },
  {
    id: 8,
    title: "Madame Bovary",
    creatorIds: [11],
    type: "Book",
    genre: "Drame",
    theme: "Mariage, Société",
    period: "1857",
    relatedWorks: [],
    narrativeType: "Omniscient",
    pageCount: 380,
  },
  {
    id: 9,
    title: "Guernica",
    creatorIds: [12],
    type: "Painting",
    genre: "Cubisme",
    theme: "Guerre, Souffrance",
    period: "1937",
    relatedWorks: [],
    medium: "Huile",
    dimensions: { width: 349, height: 776 },
    location: "Museo Reina Sofía, Madrid",
  },
  {
    id: 10,
    title: "Le Petit Prince",
    creatorIds: [13],
    type: "Book",
    genre: "Philosophie, Fiction",
    theme: "Amitié, Imagination",
    period: "1943",
    relatedWorks: [],
    narrativeType: "Première Personne",
    pageCount: 96,
  },
  {
    id: 11,
    title: "Les Fleurs du mal",
    creatorIds: [14],
    type: "Book",
    genre: "Poésie",
    theme: "Beauté, Mélancolie",
    period: "1857",
    relatedWorks: [],
    narrativeType: "Omniscient",
    pageCount: 248,
  },
  {
    id: 12,
    title: "Le Fabuleux Destin d'Amélie Poulain",
    creatorIds: [15],
    type: "Film",
    genre: "Comédie Romantique",
    theme: "Espoir, Solitude",
    period: "2001",
    relatedWorks: [],
    duration: 122,
    studio: "Claudie Ossard Productions",
    actors: [16],
  },
  {
    id: 13,
    title: "La Nuit des morts-vivants",
    creatorIds: [17],
    type: "Film",
    genre: "Horreur",
    theme: "Survie, Terreur",
    period: "1968",
    relatedWorks: [],
    duration: 96,
    studio: "Image Ten",
    actors: [],
  },
  {
    id: 14,
    title: "Impression, soleil levant",
    creatorIds: [18],
    type: "Painting",
    genre: "Impressionnisme",
    theme: "Paysage, Lumière",
    period: "1872",
    relatedWorks: [],
    medium: "Huile",
    dimensions: { width: 48, height: 63 },
    location: "Musée Marmottan Monet, Paris",
  },
  {
    id: 15,
    title: "Le Dernier Métro",
    creatorIds: [19],
    type: "Film",
    genre: "Drame, Romance",
    theme: "Résistance, Amour",
    period: "1980",
    relatedWorks: [],
    duration: 131,
    studio: "Les Films du Carrosse",
    actors: [],
  },
  {
    id: 16,
    title: "Sunflowers",
    creatorIds: [1],
    type: "Painting",
    genre: "Post-Impressionnisme",
    theme: "Nature, Beauté",
    period: "1888",
    relatedWorks: [],
    medium: "Huile",
    dimensions: { width: 92, height: 73 },
    location: "Van Gogh Museum, Amsterdam",
  },
  {
    id: 17,
    title: "La Recherche du temps perdu",
    creatorIds: [20],
    type: "Book",
    genre: "Roman",
    theme: "Mémoire, Nostalgie",
    period: "1913",
    relatedWorks: [],
    narrativeType: "Première Personne",
    pageCount: 4215,
  },
  {
    id: 18,
    title: "La Chambre rouge",
    creatorIds: [1],
    type: "Painting",
    genre: "Expressionnisme",
    theme: "Introspection, Mystère",
    period: "1908",
    relatedWorks: [],
    medium: "Huile",
    dimensions: { width: 81, height: 100 },
    location: "Centre Pompidou, Paris",
  },
  {
    id: 19,
    title: "Le Silence des agneaux",
    creatorIds: [21],
    type: "Film",
    genre: "Thriller, Horreur",
    theme: "Traque, Psychologie",
    period: "1991",
    relatedWorks: [],
    duration: 118,
    studio: "Orion Pictures",
    actors: [],
  },
  {
    id: 20,
    title: "À la recherche de l'inconnu",
    creatorIds: [22],
    type: "Book",
    genre: "Mystère",
    theme: "Aventure, Découverte",
    period: "1920",
    relatedWorks: [],
    narrativeType: "Omniscient",
    pageCount: 400,
  },
  {
    id: 21,
    title: "Les Demoiselles d'Avignon",
    creatorIds: [12],
    type: "Painting",
    genre: "Cubisme",
    theme: "Modernité, Rébellion",
    period: "1907",
    relatedWorks: [],
    medium: "Huile",
    dimensions: { width: 243.9, height: 233.7 },
    location: "Musée d'Art Moderne, New York",
  },
];
